version: '3'
services:
  focal:
    build:
      context: .
      dockerfile: ./docker/focal/Dockerfile
    container_name: focal
    tty: true
    command: bash
    environment:
      # https://medium.com/@mreichelt/how-to-show-x11-windows-within-docker-on-mac-50759f4b65cb
      - DISPLAY=docker.for.mac.localhost:0
